Enterprise Patterns/ActiveRecord/ActiveRecord.WebUI.MVC/Controllers/BlogController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ActiveRecord.Model;

namespace ActiveRecord.WebUI.MVC.Controllers
{
    public class BlogController : Controller
    {
        //
        // GET: /Blog/

        public ActionResult Index()
        {
            Post[] posts = Post.FindAll();

            if (posts.Count() > 0)
            {
                ViewBag.AllPosts = posts;
                ViewBag.LatestPost = Post.FindLastestPost();

                return View();
            }

            return RedirectToAction("Create");
        }

        [HttpPost]
        public ActionResult CreateComment(int id, FormCollection collection)
        {
            Post post = Post.Find(id);

            Comment comment = new Comment
                {
                    Post = post,
                    Author = collection["Author"],
                    Text = collection["Comment"],
                    DateAdded = DateTime.Now
                };
            
            comment.Save();

            return RedirectToAction("Detail", new { id = post.Id });
        }

        public ActionResult Detail(int id)
        {
            ViewBag.AllPosts = Post.FindAll();
            ViewBag.LatestPost = Post.Find(id);

            return View("Index");
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(Post post)
        {
            post.DateAdded = DateTime.Now;
            post.Save();
            return RedirectToAction("Detail", new { id = post.Id });
        }
    }
}

Enterprise Patterns/ActiveRecord/ActiveRecord.WebUI.MVC/Views/Blog/Create.cshtml
@{
    ViewBag.Title = "Create";
}

<h2>Create Post</h2>

@using (Html.BeginForm())
{
    <p>
        Subject
        <br/>
        @Html.TextBox("Subject")
    </p>
    <p>Content
        <br/>
        @Html.TextArea("Text")
    </p>
    <p>
        <input type="submit" value="Create"/>
    </p>
}

Enterprise Patterns/ActiveRecord/ActiveRecord.WebUI.MVC/Views/Blog/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<div id="content">
    <h2>@ViewBag.LatestPost.Subject</h2>

    <p>posted on @ViewBag.LatestPost.DateAdded.ToLongDateString()</p>
    <p>@ViewBag.LatestPost.Text</p>
    <hr />
    Comments<br />
    @foreach (var item in ViewBag.LatestPost.Comments)
    {
        <p>@item.Author said at @item.DateAdded.ToLongDateString()
            <br />
            @item.Text
        </p>
    }

    <p>Add a comment</p>
    @using (Html.BeginForm("CreateComment", "Blog", new { id = ViewBag.LatestPost.Id }, FormMethod.Post))
    {
        <p>
            Your name<br />
            @Html.TextBox("Author")
        </p>
        <p>
            Your comment<br />
            @Html.TextArea("Comment")
        </p>
        <p>
            <input type="submit" value="Add Comment" />
        </p>
    }
</div>

<div id="rightNav">
    <h2>All posts</h2>
    <ul>
        @foreach (var item in ViewBag.AllPosts)
        {
            <li>
                @Html.ActionLink((string)item.Subject, "Detail", new { id=item.Id })
                <br/>
                @item.ShortText
            </li>
        }
    </ul>
</div>

Enterprise Patterns/ActiveRecord/ActiveRecord.WebUI.MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>@ViewBag.Title</title>
    <link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" type="text/css" />
</head>
<body>
    <div id="document">
        <div id="header">
            <h1>My Blog</h1>
        </div>
        <div id="nav">
            @Html.ActionLink("Create Post", "Create")
        </div>
        <div>
            @RenderBody()
        </div>
    </div>
</body>
</html>